export const dummyData = [
  {
    GSTIN: "01ABCD2345E6FGH",
    "Legal Name of Business": "RST Industries",
    "GSTIN Status": "Active",
    "Constitution Business": "Sole Proprietorship",
    "Taxpayer Type": "Composition",
    "Date of Registration": "19-Oct-2023",
    "State Jurisdiction details": "14 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "23FGHIJ6789K0LM",
    "Legal Name of Business": "GHI Enterprises",
    "GSTIN Status": "Active",
    "Constitution Business": "Public Limited Company",
    "Taxpayer Type": "Regular",
    "Date of Registration": "30-Nov-2023",
    "State Jurisdiction details": "55 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "89UVWXY5678Z9AB",
    "Legal Name of Business": "MNO Solutions",
    "GSTIN Status": "Active",
    "Constitution Business": "Partnership Firm",
    "Taxpayer Type": "Regular",
    "Date of Registration": "25-Sep-2023",
    "State Jurisdiction details": "36 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "67OPQRS1234T5UV",
    "Legal Name of Business": "JKL Technologies",
    "GSTIN Status": "Active",
    "Constitution Business": "Limited Liability Partnership",
    "Taxpayer Type": "Composition",
    "Date of Registration": "02-Aug-2023",
    "State Jurisdiction details": "49 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "45HIJKL7890M1NO",
    "Legal Name of Business": "QRS Ventures",
    "GSTIN Status": "Active",
    "Constitution Business": "Private Limited Company",
    "Taxpayer Type": "Regular",
    "Date of Registration": "08-Jul-2023",
    "State Jurisdiction details": "28 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "23CDEFG4567H8IJ",
    "Legal Name of Business": "LMN Corporation",
    "GSTIN Status": "Active",
    "Constitution Business": "Public Limited Company",
    "Taxpayer Type": "Composition",
    "Date of Registration": "15-Jun-2023",
    "State Jurisdiction details": "75 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "90UVWXY3456Z1AB",
    "Legal Name of Business": "PQR Innovations",
    "GSTIN Status": "Active",
    "Constitution Business": "Sole Proprietorship",
    "Taxpayer Type": "Regular",
    "Date of Registration": "12-May-2023",
    "State Jurisdiction details": "60 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "78PQRST5678U9VW",
    "Legal Name of Business": "LMN Solutions",
    "GSTIN Status": "Active",
    "Constitution Business": "Limited Liability Partnership",
    "Taxpayer Type": "Composition",
    "Date of Registration": "05-Apr-2023",
    "State Jurisdiction details": "18 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "56KLMNO1234P7QR",
    "Legal Name of Business": "DEF Industries",
    "GSTIN Status": "Active",
    "Constitution Business": "Partnership Firm",
    "Taxpayer Type": "Regular",
    "Date of Registration": "10-Mar-2023",
    "State Jurisdiction details": "32 Zone",
    "Center Jurisdiction details": "NA",
  },
  {
    GSTIN: "23FGHIJ6789K2LM",
    "Legal Name of Business": "XYZ Enterprises",
    "GSTIN Status": "Active",
    "Constitution Business": "Private Limited Company",
    "Taxpayer Type": "Regular",
    "Date of Registration": "20-Feb-2023",
    "State Jurisdiction details": "45 Zone",
    "Center Jurisdiction details": "NA",
  },
];